---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: 
    app: nginx1
  ports:
    - nodePort: 30500
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort