---
apiVersion: v1
kind: Pod
metadata:
  name: mywebapp1
  labels:
    app: nginx
spec:
  containers:
    - name: webserver1
      image: nginx:1.16
      ports:
        - containerPort: 8080